mteval/views/competitions.py
from mteval import app, converters
from flask import Blueprint, Flask, render_template, request, send_file, redirect, url_for, Response, flash, send_from_directory
from flask.ext.login import request, current_user, LoginManager, logout_user, login_required
from mteval.forms import LoginForm, RegisterForm, EditTeamForm, CompetitionForm, CompetitionEditForm
from mteval.database import teamDB, compDB
from mteval.decorators import async
from werkzeug import secure_filename
from mteval.rdf_from_csvw import CSVWtoRDF
from rdflib import Graph
from flask_rdf import flask_rdf
from HTTP4Store import HTTP4Store
import os
import time
import json

#blueprint for competitions
#prefix: "/comps"
competitions = Blueprint("competitions", __name__)
store = HTTP4Store("http://localhost:8989")

#Competition routes
@competitions.route("/")
def competitions_home():
    comps = compDB.getCompList()
    return render_template("competitions/competitions.html", comps=comps)

#Add a competition
#GET request renders a template with a form to add competitions
#POST request takes form information and adds a database entry for the competition
@competitions.route("/addCompetition/", methods=["GET", "POST"])
@login_required
def addCompetition():
    #Only admins should be allowed to add a competition
    if current_user.isAdmin == False:
        flash("You are not an admin")
        return redirect(url_for("competitions.competitions_home"))

    #Form as defined in forms.py
    form = CompetitionForm(request.form)
    if request.method == "POST" and form.validate():
        #Get the files uploaded by the admin as part of the competition
        testData = request.files["testData"]
        trainingData = request.files["trainingData"]

        #Clean the names given by the user
        testDataName = secure_filename(testData.filename)
        trainingDataName = secure_filename(trainingData.filename)
        
        #Save the files
        if testDataName != "":
            testData.save(os.path.join(app.config["UPLOAD_DIR"], testDataName))
        if trainingDataName != "":
            trainingData.save(os.path.join(app.config["UPLOAD_DIR"], trainingDataName))
        
        #Add entry in database
        res = compDB.addComp( 
            form.name.data,
            form.description.data,
            form.deadline.data,
            form.submissionFormat.data,
            form.requirements.data,
            form.organisers.data,
            form.contact.data,
            testDataName,
            trainingDataName
        )

        return redirect(url_for("competitions.competitions_home"))

    #FormAction is passed to the template so it can change the action of the submit button based on whether a competition
    #is being edited or added
    return render_template("competitions/addCompetition.html", form=form, formAction="/comps/addCompetition/")

@competitions.route("/editCompetition/<name>", methods=["GET", "POST"])
@login_required
def editCompetition(name):
    if current_user.isAdmin == False:
        flash("You are not an admin")
        return redirect(url_for("competitions_home"))    
    form = CompetitionEditForm(request.form)
    if request.method == "POST" and form.validate():
        testData = request.files["testData"]
        trainingData = request.files["trainingData"]

        ##TODO: CHANGE NAMING
        #overwrites duplicate names
        testDataName = secure_filename(testData.filename)
        trainingDataName = secure_filename(trainingData.filename)
        if testDataName != "":
            testData.save(os.path.join(app.config["UPLOAD_DIR"], testDataName))
        if trainingDataName != "":
            trainingData.save(os.path.join(app.config["UPLOAD_DIR"], trainingDataName))
        
        res = compDB.editComp( 
            name,
            form.name.data,
            form.description.data,
            form.deadline.data,
            form.submissionFormat.data,
            form.requirements.data,
            form.organisers.data,
            form.contact.data,
            testDataName,
            trainingDataName
        )

        return redirect(url_for("competitions.competitions_home"))

    comp = compDB.getCompByName(name)
    form.name.data = comp["compName"]
    form.description.data = comp["description"]
    form.deadline.data = comp["deadline"]
    form.submissionFormat.data = comp["format"]
    form.requirements.data = comp["requirements"]
    form.organisers.data = comp["organisers"]
    form.contact.data = comp["contact"]

    return render_template("competitions/addCompetition.html", form=form, formAction="/comps/editCompetition/{0}".format(name))

@competitions.route("/removeCompetition/<name>")
@login_required
def removeCompetition(name):    
    if current_user.isAdmin == False:
        flash("You are not an admin")
        return redirect(url_for("competitions.competitions_home"))

    compDB.removeComp(name)

    return redirect(url_for("competitions.competitions_home"))

@competitions.route("/submissions")
def submissionList():
    comp = request.args.get("competition")
    if comp == "":
        comp = None

    return render_template("/directoryList.html", tree = makeTree("mteval/upload", comp))
@competitions.route("/submissions/sparql", methods=["GET", "POST"])
def submissionQuery():
    if request.method == "POST":
        query = request.form.get("query")
        res = store.sparql(query)
        return json.dumps(res, indent=4)

    return render_template("sparql.html")

def makeTree(path, comp = None):
    tree = dict(name=os.path.basename(path), children=[])
    try: lst = os.listdir(path)
    except OSError:
        pass #ignore errors
    else:
        for name in lst:
            pathComp = name.split("-")[0]
            if comp != None:
                if comp == pathComp:
                    fn = os.path.join(path, name)
                    tree['children'].append(dict(name=name))
            else:
                tree['children'].append(dict(name=name))
    return tree

@competitions.route("/submissions/<name>")
def downloadFile(name):
    return send_from_directory(app.config["UPLOAD_DIR"], name)


# @competitions.route("/submissions/<name>")
# @login_required
# @flask_rdf
# def showGraph(name):
#     graph = Graph()
#     graph.parse("{0}/{1}".format("mteval/upload", name))
#     return graph

@competitions.route("/upload", methods = ["GET", "POST"])
@login_required
def uploadSubmission():
    if request.method == "POST":
        subData = request.files["file"]
        compName = request.form.get("compName")
        teamName = request.form.get("teamName")    
        
        if not allowedFile(subData.filename):
            flash("File type not accepted")
            return redirect("/comps")

        subDataName = secure_filename("{0}-{1}-{2}".format(compName, teamName, int(time.time())))
        filePath = os.path.join(app.config["UPLOAD_DIR"], subDataName)
        if subDataName != "":
            try:
                subData.save(filePath)
            except Exception:
                flash("Error saving file, please try to upload again")
                return redirect("/comps")

        teamDB.appendSub(subDataName, teamName, compName)

    convertToCSVW(filePath)
    flash("File uploaded")
    return redirect("/")        
    

def allowedFile(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1] in app.config["ALLOWED_EXTENSIONS"]
@async
def convertToCSVW(filename):
    (csvName, csvwName) = converters.SGMLToCSVW(filename)
    g = Graph()
    csvwConverter = CSVWtoRDF(g)
    csvwConverter.loadCSVW(csvName, csvwFilename=csvwName)
    csvwConverter.writeToFile("{0}.rdf".format(csvName))
    filePath = "http://127.0.0.1:5005/comps/submissions/{0}.rdf".format(os.path.basename(csvName))
    print filePath
    store.add_from_uri(filePath)

mteval/views/home.py
from flask import Blueprint, Flask, render_template, request, send_file, redirect, url_for, Response, flash
from flask.ext.login import request, current_user, LoginManager, logout_user, login_required
from mteval.forms import LoginForm, RegisterForm, EditTeamForm, CompetitionForm, CompetitionEditForm
from mteval.database import teamDB, compDB
from werkzeug import secure_filename
import os
from mteval import loginUtils

home = Blueprint("home", __name__)


#Application routes
@home.route('/')
def index():
    upcomingComps = compDB.getUpcomingCompList()
    return render_template("home/index.html", upcomingComps=upcomingComps)


###Login & registration routes
@home.route('/login', methods=["GET", "POST"])
def login():
    if current_user.is_authenticated():
        flash("You are already logged in")
        return redirect(url_for("home.index"))
    form = LoginForm(request.form)
    if request.method == "POST" and form.validate():
        status = loginUtils.loginUser(form.teamname.data, form.password.data)
        print status
        if status["isValid"] == True:
            flash("Logged in successfully")
        else:
            flash("Login failed: " + status["reason"])

        next = request.args.get("next")
        return redirect(next or url_for("home.index"))
    
    else:
        return render_template("home/login.html", form = form)

@home.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("home.login"))

@home.route('/register', methods=["GET", "POST"])
def register():
    if current_user.is_authenticated():
        flash("You are already logged in, please log out to register a new team")
        return redirect(url_for("home.index"))
    form = RegisterForm(request.form)
    if request.method == "POST" and form.validate():
        #returns dict {success: Bool, reason: String}
        res = teamDB.addTeam( 
            form.teamname.data,
            form.email.data, 
            form.organisation.data,
            loginUtils.hashPassword(form.password.data)
        )
        if res["success"] == True:
            flash("Registration successful")
            return redirect(url_for("home.login"))
        else: 
            flash("Registration failed: " + res["reason"])
            return redirect(url_for("home.register"))

    return render_template("home/register.html", form = form)

mteval/templates/addCompetition.html
{% extends "base.html" %}
{% from "formhelpers.html" import render_field %}

{% block content %}
<form method="POST" action="/addCompetition" enctype="multipart/form-data">
    <dl>{{ render_field(form.name) }}</dl>
    <dl>{{ render_field(form.description) }}</dl>
    <dl>{{ render_field(form.deadline) }}</dl>
    <dl>{{ render_field(form.submissionFormat) }}</dl>
    <dl>{{ render_field(form.requirements) }}</dl>
	<dl>{{ render_field(form.organisers) }}</dl>
    <dl>{{ render_field(form.contact) }}</dl>
    <dl>{{ render_field(form.testData) }}</dl>
    <dl>{{ render_field(form.trainingData) }}</dl>
    
    <p><input type="submit" value="Submit"></p>
</form>


{% endblock %}

mteval/templates/adminPanel.html
{% extends "base.html" %}

{% block content %}
	<div class="contentsWrapper">
	<div class="contents">
		<div>
			<h1 class="options">Admin panel</h1>
			<div class="panel-group" id="accordian">
				<div class="panel panel-default">
					<div class="panel-heading">
						 <a class="panel-title" data-toggle="collapse" data-parent="" href="#collapse-teamList">Edit team information</a>
					</div>
					<div id="collapse-teamList" class="panel-collapse collapse">
						<div class="panel-body">
							{%if teams|length > 0 %}			
							<table style="width:100%">
								<tr>
									<th>Email</th>
									<th>Team Name</th>
									
								</tr>
								{% for team in teams %}
									<tr>
										<td>{{team.email}}</td>
										<td>{{team.teamName}}</td>
										<td><a href="/editTeam/{{team.teamName}}" >Edit team information</a></td>
									</tr>
								{% endfor %}
								{% endif %}
							</table>
						</div>
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading">
						 <a class="panel-title" data-toggle="collapse" data-parent="" href="#panel-element-285251">Pending teams</a>
					</div>
					<div id="panel-element-285251" class="panel-collapse collapse">
						<div class="panel-body">
							{%if pendingTeams|length > 0 %}			
								<table style="width:100%">
									<tr>
										<th>Email</th>
										<th>Team Name</th>
										<th colspan="2"></th>
									</tr>
									{% for team in pendingTeams %}
										<tr>
											<td>{{team.email}}</td>
											<td>{{team.teamName}}</td>
											<td><a href="/acceptTeam/{{team.teamName}}" >Accept</a></td>
											<td><a href="/rejectTeam/{{team.teamName}}" >Reject</a></td>
										</tr>
									{% endfor %}
								</table>
							{% else %}
								<h4>No Pending Teams</h4>
							{%endif%}
						</div>
					</div>
				</div>
			</div>

		</div>
	</div>
	</div>
{% endblock %}

mteval/templates/base.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "bootstrap/fixes.html" as fixes %}

{% block title %} MTEval {% endblock %}
{% block navbar %}
	    <div class="navbar navbar-default"> 
		    <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
      </button>
      <a class="navbar-brand" href="{{ url_for('home.index') }}">MTEval</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class=""><a href="#">About <span class="sr-only">(current)</span></a></li>
        <li><a href="{{url_for('competitions.competitions_home')}}">Competitions</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        {% if current_user.isAdmin %}
          <li><a href="{{url_for('admin.adminPanel')}}">Admin panel</a></li>
        {% endif %}
      	{% if current_user.is_authenticated() %}
          <li><a href="/teams/editTeam/{{current_user.teamName}}">My Team</a></li>
        	<li><a href="{{url_for('home.logout')}}">Logout</a></li>
        {% else %}
        	<li><a href="{{url_for('home.login')}}">Login</a></li>
        {% endif %}
        <li><a href="{{url_for('home.register')}}">Register</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
	    </div>
      {% with messages = get_flashed_messages() %}
  {% if messages %}
    <ul class=flashes>
    {% for message in messages %}
      <li>{{ message }}</li>
    {% endfor %}
    </ul>
  {% endif %}
{% endwith %}
{% endblock %}
{% block content %}

{% endblock %}

mteval/templates/competitions.html
{% extends "base.html" %}

{% block content %}
<h2> Competitions </h2>

{% if current_user.isAdmin %}
<a href="{{url_for('addCompetition')}}">Add a competition</a>
{% endif %}

<div class="panel-group" id="accordian">
{%if comps|length > 0 %}			
	{% for comp in comps %}	
		<div class="panel panel-default">
			<div class="panel-heading">
				 <a class="panel-title" data-toggle="collapse" data-parent="" href="#collapse-{{comp._id}}">{{comp.compName}}</a>
			</div>
			<div id="collapse-{{comp._id}}" class="panel-collapse collapse">
				<div class="panel-body">
					<table style="width:100%">
						<tr>
							<td><strong>Description</strong></td>
							<td>{{comp.description}}</td>	
						</tr>
						<tr>
							<td><strong>Deadline</strong></td>
							<td>{{comp.deadline}}</td>	
						</tr>
						<tr>
							<td><strong>Format</strong></td>
							<td>{{comp.format}}</td>	
						</tr>
						<tr>
							<td><strong>Requirements</strong></td>
							<td>{{comp.requirements}}</td>	
						</tr>
						<tr>
							<td><strong>Organiser</strong></td>
							<td>{{comp.organiser}}</td>	
						</tr>
						<tr>
							<td><strong>Contact</strong></td>
							<td>{{comp.contact}}</td>	
						</tr>
						<tr>
							<td><strong>Test Data</strong></td>
							<td><a href="upload/{{comp.testData}}">{{comp.testData}}</td>	
						</tr>
						<tr>
							<td><strong>Training Data</strong></td>
							<td><a href="upload/{{comp.trainingData}}">{{comp.trainingData}}</a></td>	
						</tr>
					</table>
				</div>
			</div>
		</div>
	{% endfor %}
{% endif %}
</div>

{% endblock %}

mteval/templates/directoryList.html
<!doctype html>
<title>Submissions</title>
<ul id="submissionList">
{%- for item in tree.children recursive %}
    <li id="submission"><a href="/comps/submissions/{{item.name}}">{{ item.name }}</a>
{%- endfor %}
</ul>

mteval/templates/editTeam.html
{% extends "base.html" %}

{% from "formhelpers.html" import render_field %}

{% block content %}
<table style="padding:5px; border-spacing:15px">
	<tr>
		<th></th>
		<th>Current</th>
	</tr>
		<tr>
			<td><strong>Team name</strong></td>
			<td>{{team.teamName}}</td>
		</tr>
		<tr>
			<td><strong>Email </strong></td>
			<td>{{team.email}}</td>
		</tr>
		<tr>
			<td><strong>Organisation</strong></td>
			<td>{{team.organisation}}</td>
		</tr>
</table>

<br />
<form method="POST" action="/editTeam/{{team.teamName}}">
    <dl>{{ render_field(form.teamname) }}</dl>
    <dl>{{ render_field(form.email) }}</dl>
    <dl>{{ render_field(form.organisation) }}</dl>
    {% if current_user.teamName|string() == team.teamName|string() %}
    <dl>{{ render_field(form.password) }}</dl>
    <dl>{{ render_field(form.confirm) }}</dl>
    {% endif %}
	<p><input type="submit" value="Submit"></p>
</form>
{% endblock %}

mteval/templates/formhelpers.html
{% macro render_field(field) %}
  <dt>{{ field.label }}
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>
{% endmacro %}

mteval/templates/sparql.html
<form method="post" id="form">
<textarea name="query" form="form">PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT * WHERE {
 ?s ?p ?o
} LIMIT 10
</textarea>
<input type="submit" value="Submit!" >
</form>